export const ASYNC_ACTION_STARTED = 'ASYNC_ACTION_STARTED';
export const ASYNC_ACTION_FINISHED = 'ASYNC_ACTION_FINISHED';
export const ASYNC_ACTION_ERROR = 'ASYNC_ACTION_ERROR';
export const CLIENT_TOKEN_FETCHED = 'CLIENT_TOKEN_FETCHED';
export const CUSTOMER_CREATED = 'CUSTOMER_CREATED';
export const CUSTOMER_LOGGED_IN = 'CUSTOMER_LOGGED_IN';
export const CUSTOMER_LOGGED_OUT = 'CUSTOMER_LOGGED_OUT';